---
- name: Review custom virtualenvs and pull requirements
  hosts: all
  become: true
  tasks:
    - name: Include venv role
      include_role:
        name: registry.redhat.io/ansible-automation-platform-22/ee-29-rhel8:latest
